language: objective-c
osx_image: xcode11.2

env:
  global:
  - WORKSPACE=PokerCard.xcworkspace
  - SCHEME="PokerCard"
  - EXAMPLE_SCHEME="Example"
  matrix:
  - DESTINATION="platform=iOS Simulator,name=iPhone 8"

script:
- set -o pipefail
- xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty
- xcodebuild clean build -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" | xcpretty
- pod lib lint

before_deploy:
- carthage build --archive
deploy:
  provider: releases
  file: PokerCard.framework.zip
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    repo: iWeslie/PokerCard
    tags: true
