language: objective-c
osx_image: xcode12.2

env:
  global:
  - WORKSPACE=PokerCard.xcworkspace
  - SCHEME="PokerCard"
  - EXAMPLE_SCHEME="Example"
  
script:
- set -o pipefail
- xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 11' | xcpretty
- xcodebuild clean build -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 11' | xcpretty

deploy:
  provider: releases
  file: PokerCard.framework.zip
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    repo: iWeslie/PokerCard
    tags: true
